steps:
  - name: 'gcr.io/cloud-builders/go:debian'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
    find . -type d -maxdepth 1 | grep -Ev "vendor|.git|gopath|integration_tests" | xargs /builder/bin/go.bash test
  - name: 'gcr.io/cloud-builders/go:debian'
    args: ['build', '-o', 'cloud-build-local', 'github.com/GoogleCloudPlatform/cloud-build-local']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', './shell-scripts/init-dev.sh']
