steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "Please enter 1 bash command per line"
          ls -la
          gcloud version
          ./init-dev.sh
 
